server:
  port: 8081

spring:
  application:
    name: ms-orders

  kafka:
    bootstrap-servers: kafka:29092

    producer:
      key:
        serializer: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: orders-group
      auto-offset-reset: earliest
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

topics:
  input:
    payed: payed_orders
    sent: sent_orders
  output: new_orders
  partitions: 4

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
