server:
  port: 8081

spring:
  application:
    name: ms-orders

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: orders-group

topics:
  input:
    payed: payed_orders
    sent: sent_orders
  output: new_orders
