server:
  port: 8083

spring:
  application:
    name: ms-shipping

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: shipping-group

topics:
  input: payed_orders
  output: sent_orders
