server:
  port: 8082

spring:
  application:
    name: ms-payment

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-group

topics:
  input: new_orders
  output: payed_orders
