server:
  port: 8082

spring:
  application:
    name: ms-payment

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key:
        serializer: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer: org.springframework.kafka.support.serializer.JsonSerializer

topics:
  input: new_orders
  output: payed_orders

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.web: INFO