server:
  port: 8084

spring:
  application:
    name: ms-notifications

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notifications-group

topics:
  input:
    sent: sent_orders
