server:
  port: 8084

spring:
  application:
    name: ms-notifications

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

  kafka:
    bootstrap-servers: kafka:29092

    producer:
      key:
        serializer: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: notifications-group
      auto-offset-reset: earliest
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

topics:
  input:
    sent: sent_orders
  partitions: 4

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.mail: DEBUG