server:
  port: 8084

spring:
  application:
    name: ms-notifications

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notifications-group

topics:
  input:
    sent: sent_orders
  partitions: 4

logging:
  level:
    org.springframework.mail: DEBUG